### ISSUE TITLE
Equation 4 in paper

### ISSUE THREAD

**Issue by sonnguyen129** [NJUHuoJing/MAST#6]
Hi @NJUHuoJing , I have read your paper carefully but I don't understand how to have equation 4 from equation 2. Can you explain it for me?

**Comment by NJUHuoJing** [comment]
Hi, you may check the supplementary of our paper, which provides the detailed steps of the transformation of Eq. 2 to Eq. 4. Feel free to contact us if you still have questions. The supplementary is in this link. https://openaccess.thecvf.com/content/ICCV2021/supplemental/Huo_Manifold_Alignment_for_ICCV_2021_supplemental.pdf

**Comment by sonnguyen129** [comment]
Thank you for your reply. I will re-open this issue if I have any questions in the future.
